application: rank
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /vote/.*
  script: vote.app

- url: /category/.*
  script: category.app
  login: required

- url: /item/.*
  script: item.app
  login: required

- url: /.*
  script: rank.app

libraries:
- name: jinja2
  version: latest
